/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 104
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 54
#define ALIAS_COUNT 3
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 2
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_COMMA = 1,
  anon_sym_PIPE = 2,
  anon_sym_COLON = 3,
  anon_sym_AT = 4,
  aux_sym_role_token1 = 5,
  sym_options = 6,
  sym_file_name = 7,
  sym_file_extension = 8,
  anon_sym_DOT = 9,
  anon_sym_LF = 10,
  anon_sym_script = 11,
  anon_sym_variables = 12,
  anon_sym_late_variables = 13,
  anon_sym_config = 14,
  anon_sym_include = 15,
  anon_sym_pyexit = 16,
  anon_sym_info = 17,
  anon_sym_file = 18,
  anon_sym_PERCENT = 19,
  sym_alpha_numeric = 20,
  sym__content_line = 21,
  sym__comment_line = 22,
  sym_document = 23,
  sym_section = 24,
  sym_bash_section = 25,
  sym_txt_section = 26,
  sym_js_section = 27,
  sym_python_section = 28,
  sym_file_section = 29,
  sym_tag = 30,
  sym_tags = 31,
  sym_role = 32,
  sym_file_name_and_extension = 33,
  sym_file = 34,
  sym_bash_section_names = 35,
  sym_js_section_names = 36,
  sym_python_section_names = 37,
  sym_txt_section_names = 38,
  sym__file_section_name = 39,
  sym_bash_section_header = 40,
  sym_txt_section_header = 41,
  sym_js_section_header = 42,
  sym_python_section_header = 43,
  sym__file_section_header = 44,
  sym_js_line = 45,
  sym_js_line_and_tags = 46,
  aux_sym__js_and_tags_content = 47,
  sym_raw_content = 48,
  sym_comment_block = 49,
  aux_sym_document_repeat1 = 50,
  aux_sym_tags_repeat1 = 51,
  aux_sym_raw_content_repeat1 = 52,
  aux_sym_comment_block_repeat1 = 53,
  alias_sym_file_content = 54,
  alias_sym_python_content = 55,
  alias_sym_txt_content = 56,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COMMA] = ",",
  [anon_sym_PIPE] = "|",
  [anon_sym_COLON] = ":",
  [anon_sym_AT] = "@",
  [aux_sym_role_token1] = "role_token1",
  [sym_options] = "options",
  [sym_file_name] = "file_name",
  [sym_file_extension] = "file_extension",
  [anon_sym_DOT] = ".",
  [anon_sym_LF] = "\n",
  [anon_sym_script] = "script",
  [anon_sym_variables] = "variables",
  [anon_sym_late_variables] = "late_variables",
  [anon_sym_config] = "config",
  [anon_sym_include] = "include",
  [anon_sym_pyexit] = "pyexit",
  [anon_sym_info] = "info",
  [anon_sym_file] = "file",
  [anon_sym_PERCENT] = "%",
  [sym_alpha_numeric] = "alpha_numeric",
  [sym__content_line] = "_content_line",
  [sym__comment_line] = "_comment_line",
  [sym_document] = "document",
  [sym_section] = "section",
  [sym_bash_section] = "bash_section",
  [sym_txt_section] = "txt_section",
  [sym_js_section] = "js_section",
  [sym_python_section] = "python_section",
  [sym_file_section] = "file_section",
  [sym_tag] = "tag",
  [sym_tags] = "tags",
  [sym_role] = "role",
  [sym_file_name_and_extension] = "file_name_and_extension",
  [sym_file] = "file",
  [sym_bash_section_names] = "section_name",
  [sym_js_section_names] = "section_name",
  [sym_python_section_names] = "section_name",
  [sym_txt_section_names] = "section_name",
  [sym__file_section_name] = "section_name",
  [sym_bash_section_header] = "bash_section_header",
  [sym_txt_section_header] = "txt_section_header",
  [sym_js_section_header] = "js_section_header",
  [sym_python_section_header] = "python_section_header",
  [sym__file_section_header] = "_file_section_header",
  [sym_js_line] = "js_line",
  [sym_js_line_and_tags] = "js_line_and_tags",
  [aux_sym__js_and_tags_content] = "_js_and_tags_content",
  [sym_raw_content] = "bash_content",
  [sym_comment_block] = "comment_block",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_tags_repeat1] = "tags_repeat1",
  [aux_sym_raw_content_repeat1] = "raw_content_repeat1",
  [aux_sym_comment_block_repeat1] = "comment_block_repeat1",
  [alias_sym_file_content] = "file_content",
  [alias_sym_python_content] = "python_content",
  [alias_sym_txt_content] = "txt_content",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_AT] = anon_sym_AT,
  [aux_sym_role_token1] = aux_sym_role_token1,
  [sym_options] = sym_options,
  [sym_file_name] = sym_file_name,
  [sym_file_extension] = sym_file_extension,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_script] = anon_sym_script,
  [anon_sym_variables] = anon_sym_variables,
  [anon_sym_late_variables] = anon_sym_late_variables,
  [anon_sym_config] = anon_sym_config,
  [anon_sym_include] = anon_sym_include,
  [anon_sym_pyexit] = anon_sym_pyexit,
  [anon_sym_info] = anon_sym_info,
  [anon_sym_file] = anon_sym_file,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [sym_alpha_numeric] = sym_alpha_numeric,
  [sym__content_line] = sym__content_line,
  [sym__comment_line] = sym__comment_line,
  [sym_document] = sym_document,
  [sym_section] = sym_section,
  [sym_bash_section] = sym_bash_section,
  [sym_txt_section] = sym_txt_section,
  [sym_js_section] = sym_js_section,
  [sym_python_section] = sym_python_section,
  [sym_file_section] = sym_file_section,
  [sym_tag] = sym_tag,
  [sym_tags] = sym_tags,
  [sym_role] = sym_role,
  [sym_file_name_and_extension] = sym_file_name_and_extension,
  [sym_file] = sym_file,
  [sym_bash_section_names] = sym_bash_section_names,
  [sym_js_section_names] = sym_bash_section_names,
  [sym_python_section_names] = sym_bash_section_names,
  [sym_txt_section_names] = sym_bash_section_names,
  [sym__file_section_name] = sym_bash_section_names,
  [sym_bash_section_header] = sym_bash_section_header,
  [sym_txt_section_header] = sym_txt_section_header,
  [sym_js_section_header] = sym_js_section_header,
  [sym_python_section_header] = sym_python_section_header,
  [sym__file_section_header] = sym__file_section_header,
  [sym_js_line] = sym_js_line,
  [sym_js_line_and_tags] = sym_js_line_and_tags,
  [aux_sym__js_and_tags_content] = aux_sym__js_and_tags_content,
  [sym_raw_content] = sym_raw_content,
  [sym_comment_block] = sym_comment_block,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_tags_repeat1] = aux_sym_tags_repeat1,
  [aux_sym_raw_content_repeat1] = aux_sym_raw_content_repeat1,
  [aux_sym_comment_block_repeat1] = aux_sym_comment_block_repeat1,
  [alias_sym_file_content] = alias_sym_file_content,
  [alias_sym_python_content] = alias_sym_python_content,
  [alias_sym_txt_content] = alias_sym_txt_content,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_role_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_options] = {
    .visible = true,
    .named = true,
  },
  [sym_file_name] = {
    .visible = true,
    .named = true,
  },
  [sym_file_extension] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_script] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_variables] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_late_variables] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_config] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_include] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pyexit] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_info] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_file] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [sym_alpha_numeric] = {
    .visible = true,
    .named = true,
  },
  [sym__content_line] = {
    .visible = false,
    .named = true,
  },
  [sym__comment_line] = {
    .visible = false,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_bash_section] = {
    .visible = true,
    .named = true,
  },
  [sym_txt_section] = {
    .visible = true,
    .named = true,
  },
  [sym_js_section] = {
    .visible = true,
    .named = true,
  },
  [sym_python_section] = {
    .visible = true,
    .named = true,
  },
  [sym_file_section] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_tags] = {
    .visible = true,
    .named = true,
  },
  [sym_role] = {
    .visible = true,
    .named = true,
  },
  [sym_file_name_and_extension] = {
    .visible = true,
    .named = true,
  },
  [sym_file] = {
    .visible = true,
    .named = true,
  },
  [sym_bash_section_names] = {
    .visible = true,
    .named = true,
  },
  [sym_js_section_names] = {
    .visible = true,
    .named = true,
  },
  [sym_python_section_names] = {
    .visible = true,
    .named = true,
  },
  [sym_txt_section_names] = {
    .visible = true,
    .named = true,
  },
  [sym__file_section_name] = {
    .visible = true,
    .named = true,
  },
  [sym_bash_section_header] = {
    .visible = true,
    .named = true,
  },
  [sym_txt_section_header] = {
    .visible = true,
    .named = true,
  },
  [sym_js_section_header] = {
    .visible = true,
    .named = true,
  },
  [sym_python_section_header] = {
    .visible = true,
    .named = true,
  },
  [sym__file_section_header] = {
    .visible = false,
    .named = true,
  },
  [sym_js_line] = {
    .visible = true,
    .named = true,
  },
  [sym_js_line_and_tags] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__js_and_tags_content] = {
    .visible = false,
    .named = false,
  },
  [sym_raw_content] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_block] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tags_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_raw_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_file_content] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_python_content] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_txt_content] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = alias_sym_txt_content,
  },
  [2] = {
    [1] = alias_sym_python_content,
  },
  [3] = {
    [2] = alias_sym_file_content,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym_raw_content, 4,
    sym_raw_content,
    alias_sym_file_content,
    alias_sym_python_content,
    alias_sym_txt_content,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 20,
  [29] = 22,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 9,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 8,
  [99] = 56,
  [100] = 100,
  [101] = 101,
  [102] = 82,
  [103] = 103,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(55);
      ADVANCE_MAP(
        '%', 87,
        ',', 56,
        '.', 68,
        ':', 58,
        '@', 59,
        'c', 120,
        'f', 107,
        'i', 117,
        'l', 89,
        'p', 133,
        's', 96,
        'v', 91,
        '|', 57,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(69);
      if (lookahead == '@') ADVANCE(59);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(62);
      if (lookahead != 0) ADVANCE(63);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != '.') ADVANCE(66);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(3);
      if (lookahead == '@') ADVANCE(60);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(64);
      if (lookahead != 0 &&
          lookahead != '.') ADVANCE(66);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(70);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      END_STATE();
    case 5:
      if (lookahead == '\n') SKIP(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(61);
      END_STATE();
    case 6:
      if (lookahead == '_') ADVANCE(50);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(48);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(12);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(42);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(13);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(43);
      END_STATE();
    case 12:
      if (lookahead == 'b') ADVANCE(34);
      END_STATE();
    case 13:
      if (lookahead == 'b') ADVANCE(35);
      END_STATE();
    case 14:
      if (lookahead == 'c') ADVANCE(39);
      if (lookahead == 'f') ADVANCE(26);
      if (lookahead == 'i') ADVANCE(36);
      if (lookahead == 'l') ADVANCE(7);
      if (lookahead == 'p') ADVANCE(52);
      if (lookahead == 's') ADVANCE(15);
      if (lookahead == 'v') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(14);
      END_STATE();
    case 15:
      if (lookahead == 'c') ADVANCE(41);
      END_STATE();
    case 16:
      if (lookahead == 'c') ADVANCE(32);
      if (lookahead == 'f') ADVANCE(38);
      END_STATE();
    case 17:
      if (lookahead == 'd') ADVANCE(21);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(51);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(85);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(6);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(79);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(44);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 24:
      if (lookahead == 'f') ADVANCE(28);
      END_STATE();
    case 25:
      if (lookahead == 'g') ADVANCE(77);
      END_STATE();
    case 26:
      if (lookahead == 'i') ADVANCE(33);
      END_STATE();
    case 27:
      if (lookahead == 'i') ADVANCE(40);
      END_STATE();
    case 28:
      if (lookahead == 'i') ADVANCE(25);
      END_STATE();
    case 29:
      if (lookahead == 'i') ADVANCE(46);
      END_STATE();
    case 30:
      if (lookahead == 'i') ADVANCE(8);
      END_STATE();
    case 31:
      if (lookahead == 'i') ADVANCE(10);
      END_STATE();
    case 32:
      if (lookahead == 'l') ADVANCE(49);
      END_STATE();
    case 33:
      if (lookahead == 'l') ADVANCE(19);
      END_STATE();
    case 34:
      if (lookahead == 'l') ADVANCE(22);
      END_STATE();
    case 35:
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 36:
      if (lookahead == 'n') ADVANCE(16);
      END_STATE();
    case 37:
      if (lookahead == 'n') ADVANCE(24);
      END_STATE();
    case 38:
      if (lookahead == 'o') ADVANCE(83);
      END_STATE();
    case 39:
      if (lookahead == 'o') ADVANCE(37);
      END_STATE();
    case 40:
      if (lookahead == 'p') ADVANCE(47);
      END_STATE();
    case 41:
      if (lookahead == 'r') ADVANCE(27);
      END_STATE();
    case 42:
      if (lookahead == 'r') ADVANCE(30);
      END_STATE();
    case 43:
      if (lookahead == 'r') ADVANCE(31);
      END_STATE();
    case 44:
      if (lookahead == 's') ADVANCE(73);
      END_STATE();
    case 45:
      if (lookahead == 's') ADVANCE(75);
      END_STATE();
    case 46:
      if (lookahead == 't') ADVANCE(81);
      END_STATE();
    case 47:
      if (lookahead == 't') ADVANCE(71);
      END_STATE();
    case 48:
      if (lookahead == 't') ADVANCE(20);
      END_STATE();
    case 49:
      if (lookahead == 'u') ADVANCE(17);
      END_STATE();
    case 50:
      if (lookahead == 'v') ADVANCE(11);
      END_STATE();
    case 51:
      if (lookahead == 'x') ADVANCE(29);
      END_STATE();
    case 52:
      if (lookahead == 'y') ADVANCE(18);
      END_STATE();
    case 53:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(53);
      if (lookahead != 0) ADVANCE(67);
      END_STATE();
    case 54:
      if (eof) ADVANCE(55);
      if (lookahead == '%') ADVANCE(87);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(54);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_AT);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(66);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_role_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_options);
      if (lookahead == '\n') ADVANCE(69);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '@') ADVANCE(63);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_options);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_file_name);
      if (lookahead == '@') ADVANCE(60);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(64);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '.') ADVANCE(66);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_file_name);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(65);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '.') ADVANCE(66);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_file_name);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '.') ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_file_extension);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(69);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(62);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(70);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_script);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_script);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_variables);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_variables);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_late_variables);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_late_variables);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_config);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_config);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_include);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_include);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_pyexit);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_pyexit);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_info);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_info);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_file);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_file);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == '_') ADVANCE(131);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'a') ADVANCE(129);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'a') ADVANCE(94);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'a') ADVANCE(123);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'a') ADVANCE(95);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'a') ADVANCE(124);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'b') ADVANCE(115);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'b') ADVANCE(116);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'c') ADVANCE(122);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'c') ADVANCE(113);
      if (lookahead == 'f') ADVANCE(119);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'd') ADVANCE(102);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'e') ADVANCE(132);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'e') ADVANCE(86);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'e') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'e') ADVANCE(80);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'e') ADVANCE(125);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'e') ADVANCE(126);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'f') ADVANCE(109);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'g') ADVANCE(78);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'i') ADVANCE(114);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'i') ADVANCE(121);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'i') ADVANCE(106);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'i') ADVANCE(127);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'i') ADVANCE(90);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'i') ADVANCE(92);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'l') ADVANCE(130);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'l') ADVANCE(100);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'l') ADVANCE(103);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'l') ADVANCE(104);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'n') ADVANCE(97);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'n') ADVANCE(105);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'o') ADVANCE(84);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'o') ADVANCE(118);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'p') ADVANCE(128);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'r') ADVANCE(108);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'r') ADVANCE(111);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'r') ADVANCE(112);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 's') ADVANCE(74);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 's') ADVANCE(76);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 't') ADVANCE(82);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 't') ADVANCE(72);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 't') ADVANCE(101);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'u') ADVANCE(98);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'v') ADVANCE(93);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'x') ADVANCE(110);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == 'y') ADVANCE(99);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_alpha_numeric);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 2},
  [3] = {.lex_state = 0, .external_lex_state = 2},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 14},
  [6] = {.lex_state = 54, .external_lex_state = 1},
  [7] = {.lex_state = 54, .external_lex_state = 1},
  [8] = {.lex_state = 14},
  [9] = {.lex_state = 14},
  [10] = {.lex_state = 54, .external_lex_state = 3},
  [11] = {.lex_state = 0, .external_lex_state = 1},
  [12] = {.lex_state = 0, .external_lex_state = 1},
  [13] = {.lex_state = 54, .external_lex_state = 1},
  [14] = {.lex_state = 54, .external_lex_state = 1},
  [15] = {.lex_state = 0, .external_lex_state = 2},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0, .external_lex_state = 2},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 0, .external_lex_state = 3},
  [32] = {.lex_state = 0, .external_lex_state = 3},
  [33] = {.lex_state = 0, .external_lex_state = 3},
  [34] = {.lex_state = 0, .external_lex_state = 2},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 3},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 0, .external_lex_state = 2},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0, .external_lex_state = 2},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 0, .external_lex_state = 2},
  [45] = {.lex_state = 0, .external_lex_state = 2},
  [46] = {.lex_state = 0, .external_lex_state = 2},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0, .external_lex_state = 3},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 54, .external_lex_state = 3},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 54, .external_lex_state = 3},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 54, .external_lex_state = 3},
  [61] = {.lex_state = 54, .external_lex_state = 3},
  [62] = {.lex_state = 54},
  [63] = {.lex_state = 3},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 0, .external_lex_state = 3},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 4},
  [68] = {.lex_state = 0, .external_lex_state = 3},
  [69] = {.lex_state = 4},
  [70] = {.lex_state = 4},
  [71] = {.lex_state = 0, .external_lex_state = 3},
  [72] = {.lex_state = 4},
  [73] = {.lex_state = 4},
  [74] = {.lex_state = 0, .external_lex_state = 3},
  [75] = {.lex_state = 4},
  [76] = {.lex_state = 4},
  [77] = {.lex_state = 0, .external_lex_state = 3},
  [78] = {.lex_state = 0, .external_lex_state = 3},
  [79] = {.lex_state = 2},
  [80] = {.lex_state = 0, .external_lex_state = 3},
  [81] = {.lex_state = 4},
  [82] = {.lex_state = 5},
  [83] = {.lex_state = 4},
  [84] = {.lex_state = 0, .external_lex_state = 3},
  [85] = {.lex_state = 4},
  [86] = {.lex_state = 4},
  [87] = {.lex_state = 4},
  [88] = {.lex_state = 0, .external_lex_state = 3},
  [89] = {.lex_state = 4},
  [90] = {.lex_state = 0, .external_lex_state = 3},
  [91] = {.lex_state = 4},
  [92] = {.lex_state = 4},
  [93] = {.lex_state = 0, .external_lex_state = 3},
  [94] = {.lex_state = 0, .external_lex_state = 3},
  [95] = {.lex_state = 0, .external_lex_state = 3},
  [96] = {.lex_state = 0, .external_lex_state = 3},
  [97] = {.lex_state = 53},
  [98] = {.lex_state = 0, .external_lex_state = 3},
  [99] = {.lex_state = 2},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 4},
  [102] = {.lex_state = 5},
  [103] = {.lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_script] = ACTIONS(1),
    [anon_sym_variables] = ACTIONS(1),
    [anon_sym_late_variables] = ACTIONS(1),
    [anon_sym_config] = ACTIONS(1),
    [anon_sym_include] = ACTIONS(1),
    [anon_sym_pyexit] = ACTIONS(1),
    [anon_sym_info] = ACTIONS(1),
    [anon_sym_file] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [sym_alpha_numeric] = ACTIONS(1),
    [sym__content_line] = ACTIONS(1),
    [sym__comment_line] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(100),
    [sym_section] = STATE(2),
    [sym_bash_section] = STATE(34),
    [sym_txt_section] = STATE(34),
    [sym_js_section] = STATE(34),
    [sym_python_section] = STATE(34),
    [sym_file_section] = STATE(34),
    [sym_bash_section_header] = STATE(32),
    [sym_txt_section_header] = STATE(33),
    [sym_js_section_header] = STATE(10),
    [sym_python_section_header] = STATE(31),
    [sym__file_section_header] = STATE(30),
    [sym_comment_block] = STATE(2),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_comment_block_repeat1] = STATE(15),
    [anon_sym_PERCENT] = ACTIONS(3),
    [sym__comment_line] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      sym__comment_line,
    ACTIONS(7), 1,
      ts_builtin_sym_end,
    STATE(10), 1,
      sym_js_section_header,
    STATE(15), 1,
      aux_sym_comment_block_repeat1,
    STATE(30), 1,
      sym__file_section_header,
    STATE(31), 1,
      sym_python_section_header,
    STATE(32), 1,
      sym_bash_section_header,
    STATE(33), 1,
      sym_txt_section_header,
    STATE(3), 3,
      sym_section,
      sym_comment_block,
      aux_sym_document_repeat1,
    STATE(34), 5,
      sym_bash_section,
      sym_txt_section,
      sym_js_section,
      sym_python_section,
      sym_file_section,
  [40] = 11,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(11), 1,
      anon_sym_PERCENT,
    ACTIONS(14), 1,
      sym__comment_line,
    STATE(10), 1,
      sym_js_section_header,
    STATE(15), 1,
      aux_sym_comment_block_repeat1,
    STATE(30), 1,
      sym__file_section_header,
    STATE(31), 1,
      sym_python_section_header,
    STATE(32), 1,
      sym_bash_section_header,
    STATE(33), 1,
      sym_txt_section_header,
    STATE(3), 3,
      sym_section,
      sym_comment_block,
      aux_sym_document_repeat1,
    STATE(34), 5,
      sym_bash_section,
      sym_txt_section,
      sym_js_section,
      sym_python_section,
      sym_file_section,
  [80] = 13,
    ACTIONS(17), 1,
      anon_sym_script,
    ACTIONS(21), 1,
      anon_sym_pyexit,
    ACTIONS(23), 1,
      anon_sym_info,
    ACTIONS(25), 1,
      anon_sym_file,
    ACTIONS(27), 1,
      sym_alpha_numeric,
    STATE(5), 1,
      sym_tags,
    STATE(16), 1,
      sym_bash_section_names,
    STATE(17), 1,
      sym_python_section_names,
    STATE(18), 1,
      sym_txt_section_names,
    STATE(19), 1,
      sym_js_section_names,
    STATE(20), 1,
      sym_tag,
    STATE(38), 1,
      sym__file_section_name,
    ACTIONS(19), 4,
      anon_sym_variables,
      anon_sym_late_variables,
      anon_sym_config,
      anon_sym_include,
  [123] = 10,
    ACTIONS(29), 1,
      anon_sym_script,
    ACTIONS(33), 1,
      anon_sym_pyexit,
    ACTIONS(35), 1,
      anon_sym_info,
    ACTIONS(37), 1,
      anon_sym_file,
    STATE(23), 1,
      sym_python_section_names,
    STATE(24), 1,
      sym_bash_section_names,
    STATE(26), 1,
      sym_js_section_names,
    STATE(27), 1,
      sym_txt_section_names,
    STATE(37), 1,
      sym__file_section_name,
    ACTIONS(31), 4,
      anon_sym_variables,
      anon_sym_late_variables,
      anon_sym_config,
      anon_sym_include,
  [157] = 6,
    ACTIONS(41), 1,
      sym_alpha_numeric,
    ACTIONS(43), 1,
      sym__content_line,
    STATE(28), 1,
      sym_tag,
    STATE(80), 1,
      sym_tags,
    ACTIONS(39), 3,
      sym__comment_line,
      ts_builtin_sym_end,
      anon_sym_PERCENT,
    STATE(7), 3,
      sym_js_line,
      sym_js_line_and_tags,
      aux_sym__js_and_tags_content,
  [180] = 6,
    ACTIONS(47), 1,
      sym_alpha_numeric,
    ACTIONS(50), 1,
      sym__content_line,
    STATE(28), 1,
      sym_tag,
    STATE(80), 1,
      sym_tags,
    ACTIONS(45), 3,
      sym__comment_line,
      ts_builtin_sym_end,
      anon_sym_PERCENT,
    STATE(7), 3,
      sym_js_line,
      sym_js_line_and_tags,
      aux_sym__js_and_tags_content,
  [203] = 1,
    ACTIONS(53), 8,
      anon_sym_script,
      anon_sym_variables,
      anon_sym_late_variables,
      anon_sym_config,
      anon_sym_include,
      anon_sym_pyexit,
      anon_sym_info,
      anon_sym_file,
  [214] = 1,
    ACTIONS(55), 8,
      anon_sym_script,
      anon_sym_variables,
      anon_sym_late_variables,
      anon_sym_config,
      anon_sym_include,
      anon_sym_pyexit,
      anon_sym_info,
      anon_sym_file,
  [225] = 5,
    ACTIONS(41), 1,
      sym_alpha_numeric,
    ACTIONS(43), 1,
      sym__content_line,
    STATE(28), 1,
      sym_tag,
    STATE(80), 1,
      sym_tags,
    STATE(6), 3,
      sym_js_line,
      sym_js_line_and_tags,
      aux_sym__js_and_tags_content,
  [243] = 3,
    ACTIONS(59), 1,
      sym__content_line,
    STATE(12), 1,
      aux_sym_raw_content_repeat1,
    ACTIONS(57), 3,
      sym__comment_line,
      ts_builtin_sym_end,
      anon_sym_PERCENT,
  [255] = 3,
    ACTIONS(63), 1,
      sym__content_line,
    STATE(12), 1,
      aux_sym_raw_content_repeat1,
    ACTIONS(61), 3,
      sym__comment_line,
      ts_builtin_sym_end,
      anon_sym_PERCENT,
  [267] = 1,
    ACTIONS(66), 5,
      sym__content_line,
      sym__comment_line,
      ts_builtin_sym_end,
      anon_sym_PERCENT,
      sym_alpha_numeric,
  [275] = 1,
    ACTIONS(68), 5,
      sym__content_line,
      sym__comment_line,
      ts_builtin_sym_end,
      anon_sym_PERCENT,
      sym_alpha_numeric,
  [283] = 3,
    ACTIONS(72), 1,
      sym__comment_line,
    STATE(21), 1,
      aux_sym_comment_block_repeat1,
    ACTIONS(70), 2,
      ts_builtin_sym_end,
      anon_sym_PERCENT,
  [294] = 4,
    ACTIONS(74), 1,
      anon_sym_AT,
    ACTIONS(76), 1,
      sym_options,
    ACTIONS(78), 1,
      anon_sym_LF,
    STATE(50), 1,
      sym_role,
  [307] = 4,
    ACTIONS(74), 1,
      anon_sym_AT,
    ACTIONS(80), 1,
      sym_options,
    ACTIONS(82), 1,
      anon_sym_LF,
    STATE(64), 1,
      sym_role,
  [320] = 4,
    ACTIONS(74), 1,
      anon_sym_AT,
    ACTIONS(84), 1,
      sym_options,
    ACTIONS(86), 1,
      anon_sym_LF,
    STATE(49), 1,
      sym_role,
  [333] = 4,
    ACTIONS(74), 1,
      anon_sym_AT,
    ACTIONS(88), 1,
      sym_options,
    ACTIONS(90), 1,
      anon_sym_LF,
    STATE(59), 1,
      sym_role,
  [346] = 3,
    ACTIONS(94), 1,
      anon_sym_COLON,
    STATE(22), 1,
      aux_sym_tags_repeat1,
    ACTIONS(92), 2,
      anon_sym_COMMA,
      anon_sym_PIPE,
  [357] = 3,
    ACTIONS(98), 1,
      sym__comment_line,
    STATE(21), 1,
      aux_sym_comment_block_repeat1,
    ACTIONS(96), 2,
      ts_builtin_sym_end,
      anon_sym_PERCENT,
  [368] = 3,
    ACTIONS(101), 1,
      anon_sym_COLON,
    STATE(25), 1,
      aux_sym_tags_repeat1,
    ACTIONS(92), 2,
      anon_sym_COMMA,
      anon_sym_PIPE,
  [379] = 4,
    ACTIONS(74), 1,
      anon_sym_AT,
    ACTIONS(103), 1,
      sym_options,
    ACTIONS(105), 1,
      anon_sym_LF,
    STATE(54), 1,
      sym_role,
  [392] = 4,
    ACTIONS(74), 1,
      anon_sym_AT,
    ACTIONS(107), 1,
      sym_options,
    ACTIONS(109), 1,
      anon_sym_LF,
    STATE(51), 1,
      sym_role,
  [405] = 3,
    ACTIONS(114), 1,
      anon_sym_COLON,
    STATE(25), 1,
      aux_sym_tags_repeat1,
    ACTIONS(111), 2,
      anon_sym_COMMA,
      anon_sym_PIPE,
  [416] = 4,
    ACTIONS(74), 1,
      anon_sym_AT,
    ACTIONS(116), 1,
      sym_options,
    ACTIONS(118), 1,
      anon_sym_LF,
    STATE(53), 1,
      sym_role,
  [429] = 4,
    ACTIONS(74), 1,
      anon_sym_AT,
    ACTIONS(120), 1,
      sym_options,
    ACTIONS(122), 1,
      anon_sym_LF,
    STATE(55), 1,
      sym_role,
  [442] = 3,
    ACTIONS(124), 1,
      anon_sym_COLON,
    STATE(29), 1,
      aux_sym_tags_repeat1,
    ACTIONS(92), 2,
      anon_sym_COMMA,
      anon_sym_PIPE,
  [453] = 3,
    ACTIONS(126), 1,
      anon_sym_COLON,
    STATE(25), 1,
      aux_sym_tags_repeat1,
    ACTIONS(92), 2,
      anon_sym_COMMA,
      anon_sym_PIPE,
  [464] = 3,
    ACTIONS(128), 1,
      sym_file_name,
    STATE(46), 1,
      sym_file,
    STATE(72), 1,
      sym_file_name_and_extension,
  [474] = 3,
    ACTIONS(130), 1,
      sym__content_line,
    STATE(11), 1,
      aux_sym_raw_content_repeat1,
    STATE(44), 1,
      sym_raw_content,
  [484] = 3,
    ACTIONS(130), 1,
      sym__content_line,
    STATE(11), 1,
      aux_sym_raw_content_repeat1,
    STATE(39), 1,
      sym_raw_content,
  [494] = 3,
    ACTIONS(130), 1,
      sym__content_line,
    STATE(11), 1,
      aux_sym_raw_content_repeat1,
    STATE(42), 1,
      sym_raw_content,
  [504] = 1,
    ACTIONS(132), 3,
      sym__comment_line,
      ts_builtin_sym_end,
      anon_sym_PERCENT,
  [510] = 1,
    ACTIONS(134), 3,
      anon_sym_AT,
      sym_options,
      anon_sym_LF,
  [516] = 1,
    ACTIONS(136), 3,
      anon_sym_AT,
      sym_options,
      anon_sym_LF,
  [522] = 3,
    ACTIONS(138), 1,
      anon_sym_AT,
    ACTIONS(140), 1,
      sym_file_name,
    STATE(79), 1,
      sym_role,
  [532] = 3,
    ACTIONS(138), 1,
      anon_sym_AT,
    ACTIONS(142), 1,
      sym_file_name,
    STATE(103), 1,
      sym_role,
  [542] = 1,
    ACTIONS(144), 3,
      sym__comment_line,
      ts_builtin_sym_end,
      anon_sym_PERCENT,
  [548] = 1,
    ACTIONS(146), 3,
      anon_sym_AT,
      sym_options,
      anon_sym_LF,
  [554] = 1,
    ACTIONS(114), 3,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_COLON,
  [560] = 1,
    ACTIONS(148), 3,
      sym__comment_line,
      ts_builtin_sym_end,
      anon_sym_PERCENT,
  [566] = 1,
    ACTIONS(150), 3,
      anon_sym_AT,
      sym_options,
      anon_sym_LF,
  [572] = 1,
    ACTIONS(152), 3,
      sym__comment_line,
      ts_builtin_sym_end,
      anon_sym_PERCENT,
  [578] = 1,
    ACTIONS(154), 3,
      sym__comment_line,
      ts_builtin_sym_end,
      anon_sym_PERCENT,
  [584] = 1,
    ACTIONS(156), 3,
      sym__comment_line,
      ts_builtin_sym_end,
      anon_sym_PERCENT,
  [590] = 1,
    ACTIONS(158), 3,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_COLON,
  [596] = 3,
    ACTIONS(130), 1,
      sym__content_line,
    STATE(11), 1,
      aux_sym_raw_content_repeat1,
    STATE(45), 1,
      sym_raw_content,
  [606] = 2,
    ACTIONS(120), 1,
      sym_options,
    ACTIONS(122), 1,
      anon_sym_LF,
  [613] = 2,
    ACTIONS(107), 1,
      sym_options,
    ACTIONS(109), 1,
      anon_sym_LF,
  [620] = 2,
    ACTIONS(160), 1,
      sym_options,
    ACTIONS(162), 1,
      anon_sym_LF,
  [627] = 1,
    ACTIONS(164), 2,
      sym__content_line,
      sym_alpha_numeric,
  [632] = 2,
    ACTIONS(166), 1,
      sym_options,
    ACTIONS(168), 1,
      anon_sym_LF,
  [639] = 2,
    ACTIONS(170), 1,
      sym_options,
    ACTIONS(172), 1,
      anon_sym_LF,
  [646] = 2,
    ACTIONS(174), 1,
      sym_options,
    ACTIONS(176), 1,
      anon_sym_LF,
  [653] = 1,
    ACTIONS(178), 2,
      sym_options,
      anon_sym_LF,
  [658] = 1,
    ACTIONS(180), 2,
      sym__content_line,
      sym_alpha_numeric,
  [663] = 2,
    ACTIONS(182), 1,
      sym_options,
    ACTIONS(184), 1,
      anon_sym_LF,
  [670] = 2,
    ACTIONS(116), 1,
      sym_options,
    ACTIONS(118), 1,
      anon_sym_LF,
  [677] = 1,
    ACTIONS(186), 2,
      sym__content_line,
      sym_alpha_numeric,
  [682] = 1,
    ACTIONS(188), 2,
      sym__content_line,
      sym_alpha_numeric,
  [687] = 2,
    ACTIONS(41), 1,
      sym_alpha_numeric,
    STATE(41), 1,
      sym_tag,
  [694] = 1,
    ACTIONS(190), 2,
      anon_sym_AT,
      sym_file_name,
  [699] = 2,
    ACTIONS(103), 1,
      sym_options,
    ACTIONS(105), 1,
      anon_sym_LF,
  [706] = 1,
    ACTIONS(55), 1,
      sym__content_line,
  [710] = 1,
    ACTIONS(192), 1,
      anon_sym_DOT,
  [714] = 1,
    ACTIONS(194), 1,
      anon_sym_LF,
  [718] = 1,
    ACTIONS(196), 1,
      sym__content_line,
  [722] = 1,
    ACTIONS(198), 1,
      anon_sym_LF,
  [726] = 1,
    ACTIONS(200), 1,
      anon_sym_LF,
  [730] = 1,
    ACTIONS(202), 1,
      sym__content_line,
  [734] = 1,
    ACTIONS(204), 1,
      anon_sym_LF,
  [738] = 1,
    ACTIONS(206), 1,
      anon_sym_LF,
  [742] = 1,
    ACTIONS(208), 1,
      sym__content_line,
  [746] = 1,
    ACTIONS(210), 1,
      anon_sym_LF,
  [750] = 1,
    ACTIONS(212), 1,
      anon_sym_LF,
  [754] = 1,
    ACTIONS(214), 1,
      sym__content_line,
  [758] = 1,
    ACTIONS(216), 1,
      sym__content_line,
  [762] = 1,
    ACTIONS(218), 1,
      sym_file_name,
  [766] = 1,
    ACTIONS(220), 1,
      sym__content_line,
  [770] = 1,
    ACTIONS(222), 1,
      anon_sym_LF,
  [774] = 1,
    ACTIONS(224), 1,
      aux_sym_role_token1,
  [778] = 1,
    ACTIONS(226), 1,
      anon_sym_LF,
  [782] = 1,
    ACTIONS(228), 1,
      sym__content_line,
  [786] = 1,
    ACTIONS(230), 1,
      anon_sym_LF,
  [790] = 1,
    ACTIONS(232), 1,
      anon_sym_LF,
  [794] = 1,
    ACTIONS(234), 1,
      anon_sym_LF,
  [798] = 1,
    ACTIONS(236), 1,
      sym__content_line,
  [802] = 1,
    ACTIONS(238), 1,
      anon_sym_LF,
  [806] = 1,
    ACTIONS(240), 1,
      sym__content_line,
  [810] = 1,
    ACTIONS(242), 1,
      anon_sym_LF,
  [814] = 1,
    ACTIONS(244), 1,
      anon_sym_LF,
  [818] = 1,
    ACTIONS(246), 1,
      sym__content_line,
  [822] = 1,
    ACTIONS(248), 1,
      sym__content_line,
  [826] = 1,
    ACTIONS(250), 1,
      sym__content_line,
  [830] = 1,
    ACTIONS(252), 1,
      sym__content_line,
  [834] = 1,
    ACTIONS(254), 1,
      sym_file_extension,
  [838] = 1,
    ACTIONS(53), 1,
      sym__content_line,
  [842] = 1,
    ACTIONS(256), 1,
      sym_file_name,
  [846] = 1,
    ACTIONS(258), 1,
      ts_builtin_sym_end,
  [850] = 1,
    ACTIONS(260), 1,
      anon_sym_LF,
  [854] = 1,
    ACTIONS(262), 1,
      aux_sym_role_token1,
  [858] = 1,
    ACTIONS(264), 1,
      sym_file_name,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 40,
  [SMALL_STATE(4)] = 80,
  [SMALL_STATE(5)] = 123,
  [SMALL_STATE(6)] = 157,
  [SMALL_STATE(7)] = 180,
  [SMALL_STATE(8)] = 203,
  [SMALL_STATE(9)] = 214,
  [SMALL_STATE(10)] = 225,
  [SMALL_STATE(11)] = 243,
  [SMALL_STATE(12)] = 255,
  [SMALL_STATE(13)] = 267,
  [SMALL_STATE(14)] = 275,
  [SMALL_STATE(15)] = 283,
  [SMALL_STATE(16)] = 294,
  [SMALL_STATE(17)] = 307,
  [SMALL_STATE(18)] = 320,
  [SMALL_STATE(19)] = 333,
  [SMALL_STATE(20)] = 346,
  [SMALL_STATE(21)] = 357,
  [SMALL_STATE(22)] = 368,
  [SMALL_STATE(23)] = 379,
  [SMALL_STATE(24)] = 392,
  [SMALL_STATE(25)] = 405,
  [SMALL_STATE(26)] = 416,
  [SMALL_STATE(27)] = 429,
  [SMALL_STATE(28)] = 442,
  [SMALL_STATE(29)] = 453,
  [SMALL_STATE(30)] = 464,
  [SMALL_STATE(31)] = 474,
  [SMALL_STATE(32)] = 484,
  [SMALL_STATE(33)] = 494,
  [SMALL_STATE(34)] = 504,
  [SMALL_STATE(35)] = 510,
  [SMALL_STATE(36)] = 516,
  [SMALL_STATE(37)] = 522,
  [SMALL_STATE(38)] = 532,
  [SMALL_STATE(39)] = 542,
  [SMALL_STATE(40)] = 548,
  [SMALL_STATE(41)] = 554,
  [SMALL_STATE(42)] = 560,
  [SMALL_STATE(43)] = 566,
  [SMALL_STATE(44)] = 572,
  [SMALL_STATE(45)] = 578,
  [SMALL_STATE(46)] = 584,
  [SMALL_STATE(47)] = 590,
  [SMALL_STATE(48)] = 596,
  [SMALL_STATE(49)] = 606,
  [SMALL_STATE(50)] = 613,
  [SMALL_STATE(51)] = 620,
  [SMALL_STATE(52)] = 627,
  [SMALL_STATE(53)] = 632,
  [SMALL_STATE(54)] = 639,
  [SMALL_STATE(55)] = 646,
  [SMALL_STATE(56)] = 653,
  [SMALL_STATE(57)] = 658,
  [SMALL_STATE(58)] = 663,
  [SMALL_STATE(59)] = 670,
  [SMALL_STATE(60)] = 677,
  [SMALL_STATE(61)] = 682,
  [SMALL_STATE(62)] = 687,
  [SMALL_STATE(63)] = 694,
  [SMALL_STATE(64)] = 699,
  [SMALL_STATE(65)] = 706,
  [SMALL_STATE(66)] = 710,
  [SMALL_STATE(67)] = 714,
  [SMALL_STATE(68)] = 718,
  [SMALL_STATE(69)] = 722,
  [SMALL_STATE(70)] = 726,
  [SMALL_STATE(71)] = 730,
  [SMALL_STATE(72)] = 734,
  [SMALL_STATE(73)] = 738,
  [SMALL_STATE(74)] = 742,
  [SMALL_STATE(75)] = 746,
  [SMALL_STATE(76)] = 750,
  [SMALL_STATE(77)] = 754,
  [SMALL_STATE(78)] = 758,
  [SMALL_STATE(79)] = 762,
  [SMALL_STATE(80)] = 766,
  [SMALL_STATE(81)] = 770,
  [SMALL_STATE(82)] = 774,
  [SMALL_STATE(83)] = 778,
  [SMALL_STATE(84)] = 782,
  [SMALL_STATE(85)] = 786,
  [SMALL_STATE(86)] = 790,
  [SMALL_STATE(87)] = 794,
  [SMALL_STATE(88)] = 798,
  [SMALL_STATE(89)] = 802,
  [SMALL_STATE(90)] = 806,
  [SMALL_STATE(91)] = 810,
  [SMALL_STATE(92)] = 814,
  [SMALL_STATE(93)] = 818,
  [SMALL_STATE(94)] = 822,
  [SMALL_STATE(95)] = 826,
  [SMALL_STATE(96)] = 830,
  [SMALL_STATE(97)] = 834,
  [SMALL_STATE(98)] = 838,
  [SMALL_STATE(99)] = 842,
  [SMALL_STATE(100)] = 846,
  [SMALL_STATE(101)] = 850,
  [SMALL_STATE(102)] = 854,
  [SMALL_STATE(103)] = 858,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [11] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [14] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_js_section, 2, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__js_and_tags_content, 2, 0, 0),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__js_and_tags_content, 2, 0, 0), SHIFT_REPEAT(47),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__js_and_tags_content, 2, 0, 0), SHIFT_REPEAT(81),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tags, 3, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tags, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_content, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_raw_content_repeat1, 2, 0, 0),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_raw_content_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_js_line_and_tags, 3, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_js_line, 2, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_block, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [78] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [82] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_comment_block_repeat1, 2, 0, 0),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_comment_block_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [111] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tags_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tags_repeat1, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [118] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [120] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 1, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bash_section_names, 1, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_js_section_names, 1, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__file_section_header, 3, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__file_section_header, 2, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bash_section, 2, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_python_section_names, 1, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_txt_section, 2, 0, 1),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_txt_section_names, 1, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_python_section, 2, 0, 2),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file, 3, 0, 3),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_section, 2, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 1, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [162] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_js_section_header, 4, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [168] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [172] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [174] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [176] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_role, 2, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_js_section_header, 3, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_file_name_and_extension, 3, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_js_section_header, 5, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_js_section_header, 6, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__file_section_name, 1, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bash_section_header, 4, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_python_section_header, 3, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_python_section_header, 4, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_txt_section_header, 4, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_txt_section_header, 3, 0, 0),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__file_section_header, 4, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bash_section_header, 5, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_python_section_header, 5, 0, 0),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_txt_section_header, 5, 0, 0),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_name_and_extension, 4, 0, 0),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bash_section_header, 6, 0, 0),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bash_section_header, 3, 0, 0),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_python_section_header, 6, 0, 0),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_txt_section_header, 6, 0, 0),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_role, 2, 0, 0),
  [258] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__file_section_header, 3, 0, 0),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__content_line = 0,
  ts_external_token__comment_line = 1,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__content_line] = sym__content_line,
  [ts_external_token__comment_line] = sym__comment_line,
};

static const bool ts_external_scanner_states[4][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__content_line] = true,
    [ts_external_token__comment_line] = true,
  },
  [2] = {
    [ts_external_token__comment_line] = true,
  },
  [3] = {
    [ts_external_token__content_line] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_npf_external_scanner_create(void);
void tree_sitter_npf_external_scanner_destroy(void *);
bool tree_sitter_npf_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_npf_external_scanner_serialize(void *, char *);
void tree_sitter_npf_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_npf(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_npf_external_scanner_create,
      tree_sitter_npf_external_scanner_destroy,
      tree_sitter_npf_external_scanner_scan,
      tree_sitter_npf_external_scanner_serialize,
      tree_sitter_npf_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "npf",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
